import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ultra-Quiet Mechanical Keyboard',
    description: 'Experience the perfect tactile feel without the noise. Ideal for office and gaming.',
    price: 89.99,
    image: 'https://picsum.photos/seed/keyboard/600/400',
    category: 'Gadgets',
    rating: 4.8,
    reviews: 124,
    stock: 15,
  },
  {
    id: '2',
    name: 'Smart Ambient Desk Lamp',
    description: 'Adjustable brightness and color temperature with voice control integration.',
    price: 45.00,
    image: 'https://picsum.photos/seed/lamp/600/400',
    category: 'Home Decor',
    rating: 4.5,
    reviews: 89,
    stock: 20,
    has3D: true,
    modelType: 'lamp',
  },
  {
    id: '3',
    name: 'Noise Cancelling Wireless Earbuds',
    description: 'Premium sound quality with active noise cancellation and 24-hour battery life.',
    price: 129.99,
    image: 'https://picsum.photos/seed/earbuds/600/400',
    category: 'Gadgets',
    rating: 4.9,
    reviews: 210,
    stock: 10,
    has3D: true,
    modelType: 'earbuds',
  },
  {
    id: '20',
    name: 'Traditional Gold-Plated Kundan Churi Set',
    description: 'Exquisite handcrafted bridal & festive bangles set with intricate kundan stone craftsmanship.',
    price: 499.00,
    originalPrice: 750.00,
    image: 'https://images.unsplash.com/photo-1611591475819-797de2338678?w=600&auto=format&fit=crop&q=80',
    category: 'Churi Collection',
    rating: 4.9,
    reviews: 64,
    stock: 25,
  },
  {
    id: '21',
    name: 'Royal Velvet Bridal Churi Collection (24 Pcs)',
    description: 'Premium soft velvet matte finish churi set designed for weddings, Eid, and special occasions.',
    price: 650.00,
    originalPrice: 950.00,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    category: 'Churi Collection',
    rating: 4.8,
    reviews: 42,
    stock: 18,
  },
  {
    id: '22',
    name: 'Premium Multicolor Reshmi Glass Churi Set',
    description: 'Vibrant glossy traditional glass bangles with rich shimmer and smooth polished edges.',
    price: 280.00,
    originalPrice: 400.00,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    category: 'Churi Collection',
    rating: 4.7,
    reviews: 98,
    stock: 40,
  },
  {
    id: '23',
    name: 'Handcrafted Antique Brass Floral Churi / Bala',
    description: 'Vintage ethnic floral engraved brass bangles, rust-free with long-lasting antique luster.',
    price: 420.00,
    originalPrice: 590.00,
    image: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&auto=format&fit=crop&q=80',
    category: 'Churi Collection',
    rating: 4.9,
    reviews: 35,
    stock: 15,
  }
];