import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Ultra-Quiet Mechanical Keyboard',
    description: 'Experience the perfect tactile feel without the noise. Ideal for office and gaming.',
    price: 89.99,
    image: 'https://picsum.photos/seed/keyboard/600/400',
    category: 'Gadgets',
    rating: 4.8,
    reviews: 124,
    stock: 15,
  },
  {
    id: '2',
    name: 'Smart Ambient Desk Lamp',
    description: 'Adjustable brightness and color temperature with voice control integration.',
    price: 45.00,
    image: 'https://picsum.photos/seed/lamp/600/400',
    category: 'Home Decor',
    rating: 4.5,
    reviews: 89,
    stock: 20,
  },
  {
    id: '3',
    name: 'Noise Cancelling Wireless Earbuds',
    description: 'Premium sound quality with active noise cancellation and 24-hour battery life.',
    price: 129.99,
    image: 'https://picsum.photos/seed/earbuds/600/400',
    category: 'Gadgets',
    rating: 4.9,
    reviews: 210,
    stock: 10,
  },
  {
    id: '4',
    name: 'Minimalist Wooden Desk Organizer',
    description: 'Keep your workspace clean and stylish with this handcrafted wooden organizer.',
    price: 35.50,
    image: 'https://picsum.photos/seed/organizer/600/400',
    category: 'Home Decor',
    rating: 4.7,
    reviews: 56,
    stock: 30,
  },
  {
    id: '5',
    name: '4K Ultra HD Action Camera',
    description: 'Capture your adventures in stunning detail with waterproof housing and stabilization.',
    price: 199.99,
    image: 'https://picsum.photos/seed/camera/600/400',
    category: 'Gadgets',
    rating: 4.6,
    reviews: 142,
    stock: 8,
  },
  {
    id: '6',
    name: 'Ergonomic Mesh Office Chair',
    description: 'Breathable mesh back and adjustable lumbar support for all-day comfort.',
    price: 249.00,
    image: 'https://picsum.photos/seed/chair/600/400',
    category: 'Lifestyle',
    rating: 4.8,
    reviews: 320,
    stock: 12,
  },
  {
    id: '7',
    name: 'Portable Power Bank 20000mAh',
    description: 'High-capacity battery with fast charging for all your mobile devices.',
    price: 59.99,
    image: 'https://picsum.photos/seed/powerbank/600/400',
    category: 'Tech Accessories',
    rating: 4.7,
    reviews: 450,
    stock: 50,
  },
  {
    id: '8',
    name: 'Smart Fitness Tracker Watch',
    description: 'Track your heart rate, steps, and sleep with this sleek waterproof smartwatch.',
    price: 79.00,
    image: 'https://picsum.photos/seed/smartwatch/600/400',
    category: 'Gadgets',
    rating: 4.4,
    reviews: 185,
    stock: 25,
  },
  {
    id: '9',
    name: 'Ceramic Essential Oil Diffuser',
    description: 'Elegant design with ultrasonic technology for a relaxing home atmosphere.',
    price: 38.00,
    image: 'https://picsum.photos/seed/diffuser/600/400',
    category: 'Home Decor',
    rating: 4.6,
    reviews: 95,
    stock: 18,
  },
  {
    id: '10',
    name: 'Bluetooth Mechanical Numpad',
    description: 'The perfect companion for your laptop or compact keyboard setup.',
    price: 49.99,
    image: 'https://picsum.photos/seed/numpad/600/400',
    category: 'Gadgets',
    rating: 4.5,
    reviews: 64,
    stock: 22,
  },
  {
    id: '11',
    name: 'Leather Laptop Sleeve 14"',
    description: 'Premium genuine leather sleeve with soft microfiber lining for protection.',
    price: 65.00,
    image: 'https://picsum.photos/seed/sleeve/600/400',
    category: 'Tech Accessories',
    rating: 4.9,
    reviews: 112,
    stock: 15,
  },
  {
    id: '12',
    name: 'Magnetic Wireless Charger',
    description: 'Fast wireless charging with strong magnetic alignment for compatible phones.',
    price: 29.99,
    image: 'https://picsum.photos/seed/charger/600/400',
    category: 'Tech Accessories',
    rating: 4.3,
    reviews: 230,
    stock: 40,
  },
  {
    id: '13',
    name: 'Classic Leather Strap Watch',
    description: 'Elegant analog watch with genuine leather strap and minimalist dial.',
    price: 120.00,
    image: 'https://picsum.photos/seed/watch/600/400',
    category: 'Watches',
    rating: 4.8,
    reviews: 45,
    stock: 12,
  },
  {
    id: '14',
    name: 'Premium Cotton Oversized Tee',
    description: 'Soft, breathable 100% cotton t-shirt with a modern oversized fit.',
    price: 25.00,
    image: 'https://picsum.photos/seed/shirt/600/400',
    category: 'Clothing',
    rating: 4.6,
    reviews: 128,
    stock: 60,
  },
  {
    id: '15',
    name: 'Smart LED TV 55" 4K',
    description: 'Immersive viewing experience with vibrant colors and smart features.',
    price: 549.99,
    image: 'https://picsum.photos/seed/tv/600/400',
    category: 'Electronics',
    rating: 4.7,
    reviews: 82,
    stock: 5,
  },
  {
    id: '16',
    name: 'Denim Jacket - Vintage Wash',
    description: 'Classic denim jacket with a comfortable fit and timeless style.',
    price: 75.00,
    image: 'https://picsum.photos/seed/denim/600/400',
    category: 'Clothing',
    rating: 4.5,
    reviews: 34,
    stock: 20,
  },
  {
    id: '17',
    name: 'Smart Watch Series X',
    description: 'Advanced health tracking and seamless connectivity in a sleek design.',
    price: 299.00,
    image: 'https://picsum.photos/seed/smartwatch2/600/400',
    category: 'Watches',
    rating: 4.9,
    reviews: 156,
    stock: 10,
  },
  {
    id: '18',
    name: 'Linen Summer Shirt',
    description: 'Stay cool and stylish with this premium breathable linen shirt.',
    price: 45.00,
    image: 'https://picsum.photos/seed/linenshirt/600/400',
    category: 'Clothing',
    rating: 4.7,
    reviews: 88,
    stock: 25,
  },
  {
    id: '19',
    name: 'Diver Pro Automatic Watch',
    description: 'Professional grade diving watch with 200m water resistance.',
    price: 450.00,
    image: 'https://picsum.photos/seed/diverwatch/600/400',
    category: 'Watches',
    rating: 4.8,
    reviews: 22,
    stock: 5,
  }
];
